### ISSUE TITLE
Put XDLRC Generator into own directory, make it be runnable as a stand-alone script and add option for alt site ty-es

### ISSUE THREAD

**Issue by nelsobe** [byuccl/python-fpga-interchange#2]
Some suggestions:

1. Make runnable as a standalone script
2. Put into its own directory so you can have a README.md file to describe it and give instructions.
3. Since adding the alternate site type info makes it a non-standard XDLRC file, that should be off by default and controlled via a command line option.
4. Still not sure it shouldn't be its own repo with XDLRCX in the name with the original repo as a submodule... :-)  But, we can continue to discuss.

**Comment by reillymck** [comment]
This is done. I think including it here is fine. I have a commandline option for the XDLRC script that specifies if you want XDLRC+ instead of the normal XDLRC. The XDLRC object has separate functions for generating normal XDLRC and XDLRC+ as well. The README breaks down the usage of the script and documents the current status of XDLRC+.

**Comment by reillymck** [comment]
These changes are in the PrimDef branch currently.
